[2022-11-10T13:53:44.063-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dados_politicos.mkdir_temp manual__2022-11-10T16:53:30.640841+00:00 [queued]>
[2022-11-10T13:53:44.144-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dados_politicos.mkdir_temp manual__2022-11-10T16:53:30.640841+00:00 [queued]>
[2022-11-10T13:53:44.145-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T13:53:44.145-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-10T13:53:44.145-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T13:53:44.312-0300] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): mkdir_temp> on 2022-11-10 16:53:30.640841+00:00
[2022-11-10T13:53:44.316-0300] {standard_task_runner.py:55} INFO - Started process 6000 to run task
[2022-11-10T13:53:44.350-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dados_politicos', 'mkdir_temp', 'manual__2022-11-10T16:53:30.640841+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dados_politicos.py', '--cfg-path', '/var/folders/tf/5c5cm4z11mvb4z72rkp1jvxw0000gn/T/tmpf28o1mio']
[2022-11-10T13:53:44.372-0300] {standard_task_runner.py:83} INFO - Job 4: Subtask mkdir_temp
[2022-11-10T13:53:44.951-0300] {task_command.py:376} INFO - Running <TaskInstance: dados_politicos.mkdir_temp manual__2022-11-10T16:53:30.640841+00:00 [running]> on host mac-mikeias.local
[2022-11-10T13:53:45.454-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_politicos
AIRFLOW_CTX_TASK_ID=mkdir_temp
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T16:53:30.640841+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-10T16:53:30.640841+00:00
[2022-11-10T13:53:45.456-0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/tf/5c5cm4z11mvb4z72rkp1jvxw0000gn/T
[2022-11-10T13:53:45.458-0300] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir ../../dados/temp']
[2022-11-10T13:53:45.466-0300] {subprocess.py:86} INFO - Output:
[2022-11-10T13:53:45.897-0300] {subprocess.py:93} INFO - mkdir: ../../dados: No such file or directory
[2022-11-10T13:53:45.898-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2022-11-10T13:53:45.940-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mikeiasoliveira/Documents/Projetos/vote_consciente/.env/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-11-10T13:53:45.947-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=dados_politicos, task_id=mkdir_temp, execution_date=20221110T165330, start_date=20221110T165344, end_date=20221110T165345
[2022-11-10T13:53:46.319-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task mkdir_temp (Bash command failed. The command returned a non-zero exit code 1.; 6000)
[2022-11-10T13:53:46.346-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-10T13:53:46.399-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
